
/**
 * Product Interface
 * 
 * Represents a product entity as it exists in the database and API responses.
 * This is the complete product object with all fields including metadata.
 * 
 * @property id - Unique identifier for the product (optional, auto-generated by database)
 * @property name - Product name (required)
 * @property description - Product description (optional)
 * @property price - Product price in dollars (required, number)
 * @property image - URL to the product image (required, string)
 * @property quantity - Current stock quantity (required, number)
 * @property createdAt - Timestamp when product was created (optional, auto-generated)
 * @property updatedAt - Timestamp when product was last updated (optional, auto-generated)
 */
export interface Product {
    id?: number;
    name: string;
    description?: string;
    price: number;
    image: string;
    quantity: number;
    createdAt?: string;
    updatedAt?: string;
}

/**
 * ProductFormData Interface
 * 
 * Represents the data structure used in product forms (create/edit modals).
 * This interface differs from Product because:
 * - Form inputs can be empty strings before user fills them
 * - Some fields like id, createdAt, updatedAt are not user-editable
 * - Price and quantity can be empty strings during form input
 * 
 * @property name - Product name (required string)
 * @property description - Product description (required string, can be empty)
 * @property price - Product price (can be number or empty string during input)
 * @property image - URL to the product image (required string, can be empty)
 * @property quantity - Stock quantity (can be number or empty string during input)
 */
export interface ProductFormData {
    name: string;
    description: string;
    price: number | '';
    image: string;
    quantity: number | '';
}
